### ISSUE TITLE
Failed to install under node 5.1.0

### ISSUE THREAD

**Issue by marktyers** [ForbesLindesay/sync-request#38]
```
CXX(target) Release/obj.target/curllib/curllib.o
../curllib.cc:26:17: error: expected class name
class CurlLib : ObjectWrap {
                ^
../curllib.cc:59:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../curllib.cc:92:35: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Body(const Arguments& args) {
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../curllib.cc:114:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> Run(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../curllib.cc:38:55: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handle<v8::Value>
      (const v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:4349:16: note: passing argument to parameter 'isolate' here
      Isolate* isolate, FunctionCallback callback = 0,
               ^
../curllib.cc:40:42: error: 'New' is a private member of 'v8::PersistentBase<v8::FunctionTemplate>'
    s_ct = Persistent<FunctionTemplate>::New(t);
                                         ^
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:643:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../curllib.cc:40:12: error: too few arguments to function call, expected 2, have 1; did you mean '::CurlLib::New'?
    s_ct = Persistent<FunctionTemplate>::New(t);
           ^~~~~~~~~~
           ::CurlLib::New
../curllib.cc:59:24: note: '::CurlLib::New' declared here
  static Handle<Value> New(const Arguments& args) {
                       ^
../curllib.cc:41:9: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
    s_ct->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~^~
        .
../curllib.cc:41:11: error: no member named 'InstanceTemplate' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    s_ct->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~  ^
../curllib.cc:42:9: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
    s_ct->SetClassName(String::NewSymbol("CurlLib"));
    ~~~~^~
        .
../curllib.cc:42:11: error: no member named 'SetClassName' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    s_ct->SetClassName(String::NewSymbol("CurlLib"));
    ~~~~  ^
../curllib.cc:42:32: error: no member named 'NewSymbol' in 'v8::String'
    s_ct->SetClassName(String::NewSymbol("CurlLib"));
                       ~~~~~~~~^
../curllib.cc:44:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(s_ct, "run", Run);
                              ^~~~
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known
      conversion from 'Persistent<v8::FunctionTemplate>' to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
      ^
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known
      conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
class Local {
      ^
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'Persistent'
  V8_INLINE Local(Local<S> that)
            ^
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
      'Persistent<v8::FunctionTemplate>'
  V8_INLINE Local(S* that)
            ^
/Users/marktyers/.node-gyp/5.1.0/include/node/node.h:252:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate> recv,
                                                                      ^
../curllib.cc:45:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(s_ct, "body", Body);
                              ^~~~
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known
      conversion from 'Persistent<v8::FunctionTemplate>' to 'const v8::Local<v8::FunctionTemplate> &' for 1st argument
class Local {
      ^
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known
      conversion from 'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
class Local {
      ^
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'Persistent'
  V8_INLINE Local(Local<S> that)
            ^
/Users/marktyers/.node-gyp/5.1.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
      'Persistent<v8::FunctionTemplate>'
  V8_INLINE Local(S* that)
            ^
/Users/marktyers/.node-gyp/5.1.0/include/node/node.h:252:71: note: passing argument to parameter 'recv' here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate> recv,
                                                                      ^
../curllib.cc:48:21: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a pointer; maybe you meant to use '.'?
                s_ct->GetFunction());
                ~~~~^~
                    .
../curllib.cc:48:23: error: no member named 'GetFunction' in 'v8::Persistent<v8::FunctionTemplate,
      v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
                s_ct->GetFunction());
                ~~~~  ^
../curllib.cc:47:25: error: no member named 'NewSymbol' in 'v8::String'
    target->Set(String::NewSymbol("CurlLib"),
                ~~~~~~~~^
../curllib.cc:50:23: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_body_length = NODE_PSYMBOL("body_length");
                      ^
../curllib.cc:51:19: error: use of undeclared identifier 'NODE_PSYMBOL'
    sym_headers = NODE_PSYMBOL("headers");
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/curllib/curllib.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/marktyers/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/marktyers/.nvm/versions/node/v5.1.0/bin/node" "/Users/marktyers/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/marktyers/Documents/305CDE/labs/03 Asynchronous JavaScript/node_modules/http-sync
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:http-sync@0.0.5 http-sync@0.0.5 install: `node-gyp rebuild`
npm WARN install:http-sync@0.0.5 Exit status 1
```

**Comment by ForbesLindesay** [comment]
That is http-sync, this is sync-request.  This should work fine.
