### ISSUE TITLE
Error: The method must be a string.

### ISSUE THREAD

**Issue by empierre** [ForbesLindesay/sync-request#45]
works fine in a standalone module, but inside an express I have this:

/usr/bin/node /home/in/MyDomoAtHome-nodejs/mdah.js
/home/in/MyDomoAtHome-nodejs/node_modules/sync-request/index.js:37
    throw new Error(response.error.message || response.error || response);
    ^

Error: The method must be a string.
    at doRequest (/home/in/MyDomoAtHome-nodejs/node_modules/sync-request/index.js:37:11)
    at getLastVersion (/home/in/MyDomoAtHome-nodejs/mdah.js:69:9)
    at Object.<anonymous> (/home/in/MyDomoAtHome-nodejs/mdah.js:40:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

Process finished with exit code 1

**Comment by empierre** [comment]
ahhh... it overloads  var request = require("request") ...

is there a way to disenbiguate ?

**Comment by empierre** [comment]
my bad... sorry
