### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by ashlynjiang** [ForbesLindesay/sync-request#77]
I installed the latest code and got the following error

Ashlyn-Jiang-MAC:LMS-US-APITest ajiang3$ node examples/syncrequest.js 
/Users/ajiang3/intellij/LMS-US-APITest/node_modules/sync-request/index.js:3
const spawn = require('child_process').spawn;
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ajiang3/intellij/LMS-US-APITest/examples/syncrequest.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by ForbesLindesay** [comment]
You need to be using at least node v6
